# This compose setup is only meant for local development of LimitLess itself
# This is not for running your LimitLess site in docker
version: "3.0"
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      - POSTGRES_USER=limitless
      - POSTGRES_PASSWORD=limitless
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: redis:5
    restart: unless-stopped
  limitless:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      # Postgres
      - POSTGRES_USER=limitless
      - POSTGRES_PASSWORD=limitless
      - POSTGRES_DB=limitless
      - POSTGRES_HOST=postgres
      - POSTGRES_TEST_DB=limitless_test
      # Superuser
      - SUPERUSER_USERNAME=Admin
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=password
    ports:
      # Map port 8000 in the container to port 8000 on the host
      # This way we can access the forum through http://localhost:8000
      - "${MISAGO_DEVSERVER_PORT:-8000}:8000"
    depends_on:
      - postgres
      - redis
    tty: true
    volumes:
      # Map in the entire project into the container
      # This makes sure files in the container updates on the fly as we were working locally
      - .:/srv/limitless:Z
  celery:
    build: .
    command: celery -A devproject worker --loglevel=info
    environment:
      # Postgres
      - POSTGRES_USER=limitless
      - POSTGRES_PASSWORD=limitless
      - POSTGRES_DB=limitless
      - POSTGRES_HOST=postgres
      - POSTGRES_TEST_DB=limitless_test
    depends_on:
      - postgres
      - redis
    tty: true
    volumes:
      # Map in the entire project into the container
      # This makes sure files in the container updates on the fly as we were working locally
      - .:/srv/limitless:Z
  
